### ISSUE TITLE
O3가 무엇을 뜻하는지 궁금합니다.

### ISSUE THREAD

**Issue by Minseok-Hong** [certi-study/Algorithm#1]
## O3가 어떤 것을 뜻하는지 궁금합니다.

**Comment by jaejunha** [comment]
# 컴파일러의 최적화 옵션을 의미합니다.

보통 컴파일할 때  
  
**코드 -> 어셈블리어 -> 실행파일**  
  
의 과정을 거칩니다.   
  
만약 On(n = 0, 1, 2, 3)옵션을 준다면  
컴파일러가 더 최적화 된 어셈블리어를 만들고 더 빠른 실행파일을 만들게 됩니다.  
  
예시) gcc test.c -o test.out -O2  
  
n에 값에 따라 최적화가 달라지는 데, 이는 아래 사이트를 참고하세요
```
참고 자료: 
https://jinynet9.tistory.com/113
https://amornatura.tistory.com/127
```

기본적으로 문제 풀이 사이트, 예를들어 백준 같은 사이트들은
대부분 컴파일러 옵션으로 O2를 기본적으로 설정해줍니다.  
  
예시) g++ Main.cc -o Main -O2 -Wall -lm  
```
참고 자료: 
https://www.acmicpc.net/blog/view/52
```
  
만일 컴파일러 옵션에 명시하기 보다는 코드에 명시하고자 할 경우에는
#pragma GCC optimize ("O3")
와 같이 구문을 추가해주면 됩니다.
